"""add_purchase_invoice_tables

Revision ID: 9da7a87fed6e
Revises: b3c4d5e6f7g8
Create Date: 2026-02-23 19:45:19.122682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9da7a87fed6e'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_prescriptions_id'), table_name='customer_prescriptions')
    op.drop_index(op.f('ix_customer_prescriptions_shop_id'), table_name='customer_prescriptions')
    op.drop_table('customer_prescriptions')
    op.drop_index(op.f('ix_contact_records_id'), table_name='contact_records')
    op.drop_index(op.f('ix_contact_records_phone'), table_name='contact_records')
    op.drop_index(op.f('ix_contact_records_shop_id'), table_name='contact_records')
    op.drop_table('contact_records')
    op.drop_index(op.f('ix_monthly_invoice_summary_id'), table_name='monthly_invoice_summary')
    op.drop_index(op.f('ix_monthly_invoice_summary_shop_id'), table_name='monthly_invoice_summary')
    op.drop_table('monthly_invoice_summary')
    op.drop_index(op.f('ix_customer_medical_conditions_id'), table_name='customer_medical_conditions')
    op.drop_index(op.f('ix_customer_medical_conditions_shop_id'), table_name='customer_medical_conditions')
    op.drop_table('customer_medical_conditions')
    op.drop_index(op.f('ix_staff_members_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_shop_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_staff_code'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_index(op.f('ix_customer_visits_id'), table_name='customer_visits')
    op.drop_index(op.f('ix_customer_visits_shop_id'), table_name='customer_visits')
    op.drop_table('customer_visits')
    op.drop_index(op.f('ix_contact_reminders_id'), table_name='contact_reminders')
    op.drop_index(op.f('ix_contact_reminders_shop_id'), table_name='contact_reminders')
    op.drop_table('contact_reminders')
    op.drop_index(op.f('ix_customers_category'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_shop_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_expiry_alerts_id'), table_name='expiry_alerts')
    op.drop_table('expiry_alerts')
    op.drop_index(op.f('ix_purchase_invoices_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_invoice_date'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_invoice_number'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_received_date'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_shop_id'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_contact_interactions_id'), table_name='contact_interactions')
    op.drop_index(op.f('ix_contact_interactions_shop_id'), table_name='contact_interactions')
    op.drop_table('contact_interactions')
    op.drop_index(op.f('ix_contact_uploads_id'), table_name='contact_uploads')
    op.drop_index(op.f('ix_contact_uploads_shop_id'), table_name='contact_uploads')
    op.drop_table('contact_uploads')
    op.drop_index(op.f('ix_prescription_medicines_id'), table_name='prescription_medicines')
    op.drop_index(op.f('ix_prescription_medicines_shop_id'), table_name='prescription_medicines')
    op.drop_table('prescription_medicines')
    op.drop_index(op.f('ix_refill_reminders_id'), table_name='refill_reminders')
    op.drop_index(op.f('ix_refill_reminders_reminder_date'), table_name='refill_reminders')
    op.drop_index(op.f('ix_refill_reminders_shop_id'), table_name='refill_reminders')
    op.drop_table('refill_reminders')
    op.drop_index(op.f('ix_item_sales_id'), table_name='item_sales')
    op.drop_index(op.f('ix_item_sales_sale_date'), table_name='item_sales')
    op.drop_table('item_sales')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_phone'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_shop_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_customer_purchases_id'), table_name='customer_purchases')
    op.drop_index(op.f('ix_customer_purchases_purchase_date'), table_name='customer_purchases')
    op.drop_index(op.f('ix_customer_purchases_refill_reminder_date'), table_name='customer_purchases')
    op.drop_index(op.f('ix_customer_purchases_shop_id'), table_name='customer_purchases')
    op.drop_table('customer_purchases')
    op.drop_index(op.f('ix_purchase_invoice_items_id'), table_name='purchase_invoice_items')
    op.drop_index(op.f('ix_purchase_invoice_items_item_code'), table_name='purchase_invoice_items')
    op.drop_table('purchase_invoice_items')
    op.drop_index(op.f('ix_call_scripts_id'), table_name='call_scripts')
    op.drop_index(op.f('ix_call_scripts_shop_id'), table_name='call_scripts')
    op.drop_table('call_scripts')
    op.alter_column('bills', 'was_contacted_before',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bills', 'visited_but_no_purchase',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'visited_but_no_purchase',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('bills', 'was_contacted_before',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_table('call_scripts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('call_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('medical_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('purchase_history_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_talking_points', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medicines_to_discuss', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('follow_up_reminders', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('script_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('call_successful', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('call_scripts_customer_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('call_scripts_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('call_scripts_pkey'))
    )
    op.create_index(op.f('ix_call_scripts_shop_id'), 'call_scripts', ['shop_id'], unique=False)
    op.create_index(op.f('ix_call_scripts_id'), 'call_scripts', ['id'], unique=False)
    op.create_table('purchase_invoice_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purchased_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sold_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remaining_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('days_to_expiry', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_expiring_soon', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_expiring_critical', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('movement_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('seasonal_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('demand_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], name=op.f('purchase_invoice_items_invoice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_invoice_items_pkey'))
    )
    op.create_index(op.f('ix_purchase_invoice_items_item_code'), 'purchase_invoice_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_items_id'), 'purchase_invoice_items', ['id'], unique=False)
    op.create_table('customer_purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('medicine_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generic_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_generic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_prescription', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refill_reminder_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refill_reminder_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('customer_purchases_bill_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('customer_purchases_customer_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('customer_purchases_shop_id_fkey')),
    sa.ForeignKeyConstraint(['visit_id'], ['customer_visits.id'], name=op.f('customer_purchases_visit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_purchases_pkey'))
    )
    op.create_index(op.f('ix_customer_purchases_shop_id'), 'customer_purchases', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_purchases_refill_reminder_date'), 'customer_purchases', ['refill_reminder_date'], unique=False)
    op.create_index(op.f('ix_customer_purchases_purchase_date'), 'customer_purchases', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_customer_purchases_id'), 'customer_purchases', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shop_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shop_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('feedback_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mood', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('would_recommend', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('feedbacks_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedbacks_pkey'))
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chronic_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preferred_brands', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_doctor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doctor_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_visits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_purchases', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prefers_generic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('generic_education_given', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('special_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_record_id'], ['contact_records.id'], name=op.f('customer_profiles_contact_record_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('customer_profiles_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_profiles_pkey'))
    )
    op.create_index(op.f('ix_customer_profiles_shop_id'), 'customer_profiles', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_phone'), 'customer_profiles', ['phone'], unique=True)
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_table('item_sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity_sold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('profit_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('customer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['purchase_invoice_items.id'], name=op.f('item_sales_item_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], name=op.f('item_sales_purchase_invoice_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('item_sales_pkey'))
    )
    op.create_index(op.f('ix_item_sales_sale_date'), 'item_sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_item_sales_id'), 'item_sales', ['id'], unique=False)
    op.create_table('refill_reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medicine_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reminder_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notification_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notification_sent_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notification_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_responded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer_purchased', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('response_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('whatsapp_sent_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('call_reminder_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('call_reminder_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('refill_reminders_customer_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_id'], ['customer_purchases.id'], name=op.f('refill_reminders_purchase_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('refill_reminders_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refill_reminders_pkey'))
    )
    op.create_index(op.f('ix_refill_reminders_shop_id'), 'refill_reminders', ['shop_id'], unique=False)
    op.create_index(op.f('ix_refill_reminders_reminder_date'), 'refill_reminders', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_refill_reminders_id'), 'refill_reminders', ['id'], unique=False)
    op.create_table('prescription_medicines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medicine_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generic_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_quantity_prescribed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refill_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('refills_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('purchased', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['customer_prescriptions.id'], name=op.f('prescription_medicines_prescription_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('prescription_medicines_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prescription_medicines_pkey'))
    )
    op.create_index(op.f('ix_prescription_medicines_shop_id'), 'prescription_medicines', ['shop_id'], unique=False)
    op.create_index(op.f('ix_prescription_medicines_id'), 'prescription_medicines', ['id'], unique=False)
    op.create_table('contact_uploads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('processing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_contacts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_contacts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('non_whatsapp_contacts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duplicate_contacts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_errors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('contact_uploads_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_uploads_pkey'))
    )
    op.create_index(op.f('ix_contact_uploads_shop_id'), 'contact_uploads', ['shop_id'], unique=False)
    op.create_index(op.f('ix_contact_uploads_id'), 'contact_uploads', ['id'], unique=False)
    op.create_table('contact_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('interaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('interaction_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('call_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('call_successful', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact_records.id'], name=op.f('contact_interactions_contact_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('contact_interactions_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_interactions_pkey'))
    )
    op.create_index(op.f('ix_contact_interactions_shop_id'), 'contact_interactions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_contact_interactions_id'), 'contact_interactions', ['id'], unique=False)
    op.create_table('purchase_invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('received_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_items', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sold_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('has_expiring_items', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nearest_expiry_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_invoices_pkey'))
    )
    op.create_index(op.f('ix_purchase_invoices_shop_id'), 'purchase_invoices', ['shop_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_received_date'), 'purchase_invoices', ['received_date'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_invoice_number'), 'purchase_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_purchase_invoices_invoice_date'), 'purchase_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_id'), 'purchase_invoices', ['id'], unique=False)
    op.create_table('expiry_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['purchase_invoice_items.id'], name=op.f('expiry_alerts_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('expiry_alerts_pkey'))
    )
    op.create_index(op.f('ix_expiry_alerts_id'), 'expiry_alerts', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chronic_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_doctor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_visits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_purchases', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prefers_generic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('generic_education_given', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('special_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_record_id'], ['contact_records.id'], name=op.f('customers_contact_record_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('customers_shop_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('ix_customers_shop_id'), 'customers', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_category'), 'customers', ['category'], unique=False)
    op.create_table('contact_reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reminder_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reminder_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact_records.id'], name=op.f('contact_reminders_contact_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('contact_reminders_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_reminders_pkey'))
    )
    op.create_index(op.f('ix_contact_reminders_shop_id'), 'contact_reminders', ['shop_id'], unique=False)
    op.create_index(op.f('ix_contact_reminders_id'), 'contact_reminders', ['id'], unique=False)
    op.create_table('customer_visits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('staff_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('visit_purpose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prescription_brought', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('purchase_made', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('purchase_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('staff_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('customer_visits_customer_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('customer_visits_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_visits_pkey'))
    )
    op.create_index(op.f('ix_customer_visits_shop_id'), 'customer_visits', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_visits_id'), 'customer_visits', ['id'], unique=False)
    op.create_table('staff_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('max_contacts_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_contacts_assigned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_conversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('staff_members_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_members_pkey'))
    )
    op.create_index(op.f('ix_staff_members_staff_code'), 'staff_members', ['staff_code'], unique=True)
    op.create_index(op.f('ix_staff_members_shop_id'), 'staff_members', ['shop_id'], unique=False)
    op.create_index(op.f('ix_staff_members_id'), 'staff_members', ['id'], unique=False)
    op.create_table('customer_medical_conditions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('condition_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('condition_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('diagnosed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('primary_medicine', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('treatment_duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requires_monitoring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('monitoring_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_checkup_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('next_checkup_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('condition_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('customer_medical_conditions_customer_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('customer_medical_conditions_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_medical_conditions_pkey'))
    )
    op.create_index(op.f('ix_customer_medical_conditions_shop_id'), 'customer_medical_conditions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_medical_conditions_id'), 'customer_medical_conditions', ['id'], unique=False)
    op.create_table('monthly_invoice_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_invoices', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_items', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('green_invoices', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yellow_invoices', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('red_invoices', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall_sold_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expiring_items_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expired_items_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_insights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('movement_prediction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('monthly_invoice_summary_pkey'))
    )
    op.create_index(op.f('ix_monthly_invoice_summary_shop_id'), 'monthly_invoice_summary', ['shop_id'], unique=False)
    op.create_index(op.f('ix_monthly_invoice_summary_id'), 'monthly_invoice_summary', ['id'], unique=False)
    op.create_table('contact_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_staff_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_contact_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_contact_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('contact_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('whatsapp_sent_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('converted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('conversion_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uploaded_by_staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff.id'], name=op.f('contact_records_assigned_staff_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('contact_records_shop_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by_staff_id'], ['staff.id'], name=op.f('contact_records_uploaded_by_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_records_pkey'))
    )
    op.create_index(op.f('ix_contact_records_shop_id'), 'contact_records', ['shop_id'], unique=False)
    op.create_index(op.f('ix_contact_records_phone'), 'contact_records', ['phone'], unique=True)
    op.create_index(op.f('ix_contact_records_id'), 'contact_records', ['id'], unique=False)
    op.create_table('customer_prescriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prescription_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('doctor_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doctor_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clinic_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condition_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('condition_severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_chronic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('next_followup_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('followup_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('followup_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completion_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('prescription_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('customer_prescriptions_customer_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('customer_prescriptions_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_prescriptions_pkey'))
    )
    op.create_index(op.f('ix_customer_prescriptions_shop_id'), 'customer_prescriptions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_prescriptions_id'), 'customer_prescriptions', ['id'], unique=False)
    # ### end Alembic commands ###
