"""Initial migration

Revision ID: e245981beea1
Revises: 
Create Date: 2026-02-19 02:06:45.198564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e245981beea1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('plain_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_password_set', sa.Boolean(), nullable=True),
    sa.Column('created_by_super_admin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_organization_id'), 'admins', ['organization_id'], unique=False)
    op.create_index(op.f('ix_admins_phone'), 'admins', ['phone'], unique=True)
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_phone'), 'otp_verifications', ['phone'], unique=False)
    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_index(op.f('ix_super_admins_id'), 'super_admins', ['id'], unique=False)
    op.create_index(op.f('ix_super_admins_phone'), 'super_admins', ['phone'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'URGENT', 'ANNOUNCEMENT', name='notificationtype'), nullable=True),
    sa.Column('target_type', sa.Enum('SHOP', 'STAFF', name='notificationtargettype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=False),
    sa.Column('shop_code', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('created_by_admin', sa.String(), nullable=False),
    sa.Column('updated_by_admin', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_code', 'admin_id', name='unique_shop_code_per_admin')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_shop_code'), 'shops', ['shop_code'], unique=False)
    op.create_table('attendance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('work_start_time', sa.Time(), nullable=True),
    sa.Column('work_end_time', sa.Time(), nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=True),
    sa.Column('auto_checkout_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_checkout_time', sa.Time(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id')
    )
    op.create_index(op.f('ix_attendance_settings_id'), 'attendance_settings', ['id'], unique=False)
    op.create_table('notification_shop_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_shop_targets_id'), 'notification_shop_targets', ['id'], unique=False)
    op.create_table('shop_wifi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('wifi_ssid', sa.String(length=100), nullable=False),
    sa.Column('wifi_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_wifi_id'), 'shop_wifi', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('staff_code', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('plain_password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('monthly_salary', sa.Float(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('salary_eligibility_days', sa.Integer(), nullable=True),
    sa.Column('can_manage_staff', sa.Boolean(), nullable=True),
    sa.Column('can_view_analytics', sa.Boolean(), nullable=True),
    sa.Column('can_manage_inventory', sa.Boolean(), nullable=True),
    sa.Column('can_manage_customers', sa.Boolean(), nullable=True),
    sa.Column('is_password_set', sa.Boolean(), nullable=True),
    sa.Column('created_by_admin', sa.String(), nullable=False),
    sa.Column('updated_by_admin', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_phone'), 'staff', ['phone'], unique=True)
    op.create_index(op.f('ix_staff_staff_code'), 'staff', ['staff_code'], unique=True)
    op.create_index(op.f('ix_staff_uuid'), 'staff', ['uuid'], unique=True)
    op.create_table('stock_racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('rack_number', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_racks_id'), 'stock_racks', ['id'], unique=False)
    op.create_index(op.f('ix_stock_racks_rack_number'), 'stock_racks', ['rack_number'], unique=True)
    op.create_index(op.f('ix_stock_racks_shop_id'), 'stock_racks', ['shop_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_reads_id'), 'notification_reads', ['id'], unique=False)
    op.create_table('notification_staff_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_staff_targets_id'), 'notification_staff_targets', ['id'], unique=False)
    op.create_table('purchases_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_audit_id'), 'purchases_audit', ['id'], unique=False)
    op.create_index(op.f('ix_purchases_audit_shop_id'), 'purchases_audit', ['shop_id'], unique=False)
    op.create_index(op.f('ix_purchases_audit_staff_id'), 'purchases_audit', ['staff_id'], unique=False)
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('salary_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('paid_by_admin', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_records_id'), 'salary_records', ['id'], unique=False)
    op.create_table('sales_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('bill_number', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_audit_id'), 'sales_audit', ['id'], unique=False)
    op.create_index(op.f('ix_sales_audit_shop_id'), 'sales_audit', ['shop_id'], unique=False)
    op.create_index(op.f('ix_sales_audit_staff_id'), 'sales_audit', ['staff_id'], unique=False)
    op.create_table('staff_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_devices_id'), 'staff_devices', ['id'], unique=False)
    op.create_index(op.f('ix_staff_devices_mac_address'), 'staff_devices', ['mac_address'], unique=True)
    op.create_table('staff_payment_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('account_holder_name', sa.String(length=100), nullable=True),
    sa.Column('preferred_payment_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_index(op.f('ix_staff_payment_info_id'), 'staff_payment_info', ['id'], unique=False)
    op.create_table('stock_audit_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('sections_audited', sa.Integer(), nullable=True),
    sa.Column('items_audited', sa.Integer(), nullable=True),
    sa.Column('discrepancies_found', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_audit_sessions_id'), 'stock_audit_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_stock_audit_sessions_shop_id'), 'stock_audit_sessions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_stock_audit_sessions_staff_id'), 'stock_audit_sessions', ['staff_id'], unique=False)
    op.create_table('stock_sections_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('section_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['stock_racks.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_sections_audit_id'), 'stock_sections_audit', ['id'], unique=False)
    op.create_index(op.f('ix_stock_sections_audit_section_code'), 'stock_sections_audit', ['section_code'], unique=True)
    op.create_index(op.f('ix_stock_sections_audit_shop_id'), 'stock_sections_audit', ['shop_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('wifi_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('late_by_minutes', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('auto_checked_in', sa.Boolean(), nullable=True),
    sa.Column('auto_checked_out', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['staff_devices.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['wifi_id'], ['shop_wifi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_table('salary_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('salary_record_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salary_record_id'], ['salary_records.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_alerts_id'), 'salary_alerts', ['id'], unique=False)
    op.create_table('stock_items_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('quantity_software', sa.Integer(), nullable=True),
    sa.Column('quantity_physical', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('last_audit_date', sa.DateTime(), nullable=True),
    sa.Column('last_audit_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('last_audit_by_staff_name', sa.String(), nullable=True),
    sa.Column('audit_discrepancy', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_audit_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['stock_sections_audit.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_audit_batch_number'), 'stock_items_audit', ['batch_number'], unique=False)
    op.create_index(op.f('ix_stock_items_audit_id'), 'stock_items_audit', ['id'], unique=False)
    op.create_index(op.f('ix_stock_items_audit_item_name'), 'stock_items_audit', ['item_name'], unique=False)
    op.create_index(op.f('ix_stock_items_audit_shop_id'), 'stock_items_audit', ['shop_id'], unique=False)
    op.create_table('purchase_items_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases_audit.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items_audit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_audit_batch_number'), 'purchase_items_audit', ['batch_number'], unique=False)
    op.create_index(op.f('ix_purchase_items_audit_id'), 'purchase_items_audit', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_items_audit_shop_id'), 'purchase_items_audit', ['shop_id'], unique=False)
    op.create_table('sale_items_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales_audit.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items_audit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_audit_batch_number'), 'sale_items_audit', ['batch_number'], unique=False)
    op.create_index(op.f('ix_sale_items_audit_id'), 'sale_items_audit', ['id'], unique=False)
    op.create_index(op.f('ix_sale_items_audit_shop_id'), 'sale_items_audit', ['shop_id'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('staff_name', sa.String(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('adjustment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items_audit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_adjustments_id'), 'stock_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_shop_id'), 'stock_adjustments', ['shop_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_staff_id'), 'stock_adjustments', ['staff_id'], unique=False)
    op.create_table('stock_audit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=True),
    sa.Column('software_quantity', sa.Integer(), nullable=False),
    sa.Column('physical_quantity', sa.Integer(), nullable=False),
    sa.Column('discrepancy', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reason_for_discrepancy', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_staff_name', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items_audit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_audit_records_id'), 'stock_audit_records', ['id'], unique=False)
    op.create_index(op.f('ix_stock_audit_records_shop_id'), 'stock_audit_records', ['shop_id'], unique=False)
    op.create_index(op.f('ix_stock_audit_records_staff_id'), 'stock_audit_records', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_audit_records_staff_id'), table_name='stock_audit_records')
    op.drop_index(op.f('ix_stock_audit_records_shop_id'), table_name='stock_audit_records')
    op.drop_index(op.f('ix_stock_audit_records_id'), table_name='stock_audit_records')
    op.drop_table('stock_audit_records')
    op.drop_index(op.f('ix_stock_adjustments_staff_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_shop_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_id'), table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    op.drop_index(op.f('ix_sale_items_audit_shop_id'), table_name='sale_items_audit')
    op.drop_index(op.f('ix_sale_items_audit_id'), table_name='sale_items_audit')
    op.drop_index(op.f('ix_sale_items_audit_batch_number'), table_name='sale_items_audit')
    op.drop_table('sale_items_audit')
    op.drop_index(op.f('ix_purchase_items_audit_shop_id'), table_name='purchase_items_audit')
    op.drop_index(op.f('ix_purchase_items_audit_id'), table_name='purchase_items_audit')
    op.drop_index(op.f('ix_purchase_items_audit_batch_number'), table_name='purchase_items_audit')
    op.drop_table('purchase_items_audit')
    op.drop_index(op.f('ix_stock_items_audit_shop_id'), table_name='stock_items_audit')
    op.drop_index(op.f('ix_stock_items_audit_item_name'), table_name='stock_items_audit')
    op.drop_index(op.f('ix_stock_items_audit_id'), table_name='stock_items_audit')
    op.drop_index(op.f('ix_stock_items_audit_batch_number'), table_name='stock_items_audit')
    op.drop_table('stock_items_audit')
    op.drop_index(op.f('ix_salary_alerts_id'), table_name='salary_alerts')
    op.drop_table('salary_alerts')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_stock_sections_audit_shop_id'), table_name='stock_sections_audit')
    op.drop_index(op.f('ix_stock_sections_audit_section_code'), table_name='stock_sections_audit')
    op.drop_index(op.f('ix_stock_sections_audit_id'), table_name='stock_sections_audit')
    op.drop_table('stock_sections_audit')
    op.drop_index(op.f('ix_stock_audit_sessions_staff_id'), table_name='stock_audit_sessions')
    op.drop_index(op.f('ix_stock_audit_sessions_shop_id'), table_name='stock_audit_sessions')
    op.drop_index(op.f('ix_stock_audit_sessions_id'), table_name='stock_audit_sessions')
    op.drop_table('stock_audit_sessions')
    op.drop_index(op.f('ix_staff_payment_info_id'), table_name='staff_payment_info')
    op.drop_table('staff_payment_info')
    op.drop_index(op.f('ix_staff_devices_mac_address'), table_name='staff_devices')
    op.drop_index(op.f('ix_staff_devices_id'), table_name='staff_devices')
    op.drop_table('staff_devices')
    op.drop_index(op.f('ix_sales_audit_staff_id'), table_name='sales_audit')
    op.drop_index(op.f('ix_sales_audit_shop_id'), table_name='sales_audit')
    op.drop_index(op.f('ix_sales_audit_id'), table_name='sales_audit')
    op.drop_table('sales_audit')
    op.drop_index(op.f('ix_salary_records_id'), table_name='salary_records')
    op.drop_table('salary_records')
    op.drop_index(op.f('ix_purchases_audit_staff_id'), table_name='purchases_audit')
    op.drop_index(op.f('ix_purchases_audit_shop_id'), table_name='purchases_audit')
    op.drop_index(op.f('ix_purchases_audit_id'), table_name='purchases_audit')
    op.drop_table('purchases_audit')
    op.drop_index(op.f('ix_notification_staff_targets_id'), table_name='notification_staff_targets')
    op.drop_table('notification_staff_targets')
    op.drop_index(op.f('ix_notification_reads_id'), table_name='notification_reads')
    op.drop_table('notification_reads')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_stock_racks_shop_id'), table_name='stock_racks')
    op.drop_index(op.f('ix_stock_racks_rack_number'), table_name='stock_racks')
    op.drop_index(op.f('ix_stock_racks_id'), table_name='stock_racks')
    op.drop_table('stock_racks')
    op.drop_index(op.f('ix_staff_uuid'), table_name='staff')
    op.drop_index(op.f('ix_staff_staff_code'), table_name='staff')
    op.drop_index(op.f('ix_staff_phone'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_shop_wifi_id'), table_name='shop_wifi')
    op.drop_table('shop_wifi')
    op.drop_index(op.f('ix_notification_shop_targets_id'), table_name='notification_shop_targets')
    op.drop_table('notification_shop_targets')
    op.drop_index(op.f('ix_attendance_settings_id'), table_name='attendance_settings')
    op.drop_table('attendance_settings')
    op.drop_index(op.f('ix_shops_shop_code'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_super_admins_phone'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_id'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_index(op.f('ix_otp_verifications_phone'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_admins_phone'), table_name='admins')
    op.drop_index(op.f('ix_admins_organization_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
