"""Add billing tables

Revision ID: f972558b78b6
Revises: a68c04c716c2
Create Date: 2026-02-19 21:37:51.106935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f972558b78b6'
down_revision: Union[str, Sequence[str], None] = 'a68c04c716c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_sales_id'), table_name='item_sales')
    op.drop_index(op.f('ix_item_sales_sale_date'), table_name='item_sales')
    op.drop_table('item_sales')
    op.drop_index(op.f('ix_contact_uploads_id'), table_name='contact_uploads')
    op.drop_index(op.f('ix_contact_uploads_shop_id'), table_name='contact_uploads')
    op.drop_table('contact_uploads')
    op.drop_index(op.f('ix_contact_records_id'), table_name='contact_records')
    op.drop_index(op.f('ix_contact_records_phone'), table_name='contact_records')
    op.drop_index(op.f('ix_contact_records_shop_id'), table_name='contact_records')
    op.drop_table('contact_records')
    op.drop_index(op.f('ix_expiry_alerts_id'), table_name='expiry_alerts')
    op.drop_table('expiry_alerts')
    op.drop_index(op.f('ix_customer_prescriptions_id'), table_name='customer_prescriptions')
    op.drop_index(op.f('ix_customer_prescriptions_shop_id'), table_name='customer_prescriptions')
    op.drop_table('customer_prescriptions')
    op.drop_index(op.f('ix_purchase_invoices_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_invoice_date'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_invoice_number'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_received_date'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_shop_id'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_bill_items_id'), table_name='bill_items')
    op.drop_index(op.f('ix_bill_items_shop_id'), table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_phone'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_shop_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_prescription_medicines_id'), table_name='prescription_medicines')
    op.drop_index(op.f('ix_prescription_medicines_shop_id'), table_name='prescription_medicines')
    op.drop_table('prescription_medicines')
    op.drop_index(op.f('ix_purchase_invoice_items_id'), table_name='purchase_invoice_items')
    op.drop_index(op.f('ix_purchase_invoice_items_item_code'), table_name='purchase_invoice_items')
    op.drop_table('purchase_invoice_items')
    op.drop_index(op.f('ix_customer_purchases_id'), table_name='customer_purchases')
    op.drop_index(op.f('ix_customer_purchases_shop_id'), table_name='customer_purchases')
    op.drop_table('customer_purchases')
    op.drop_index(op.f('ix_contact_reminders_id'), table_name='contact_reminders')
    op.drop_index(op.f('ix_contact_reminders_shop_id'), table_name='contact_reminders')
    op.drop_table('contact_reminders')
    op.drop_index(op.f('ix_call_scripts_id'), table_name='call_scripts')
    op.drop_index(op.f('ix_call_scripts_shop_id'), table_name='call_scripts')
    op.drop_table('call_scripts')
    op.drop_index(op.f('ix_refill_reminders_id'), table_name='refill_reminders')
    op.drop_index(op.f('ix_refill_reminders_shop_id'), table_name='refill_reminders')
    op.drop_table('refill_reminders')
    op.drop_index(op.f('ix_bills_bill_number'), table_name='bills')
    op.drop_index(op.f('ix_bills_created_at'), table_name='bills')
    op.drop_index(op.f('ix_bills_customer_phone'), table_name='bills')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_shop_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_staff_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_customer_medical_conditions_id'), table_name='customer_medical_conditions')
    op.drop_index(op.f('ix_customer_medical_conditions_shop_id'), table_name='customer_medical_conditions')
    op.drop_table('customer_medical_conditions')
    op.drop_index(op.f('ix_monthly_invoice_summary_id'), table_name='monthly_invoice_summary')
    op.drop_index(op.f('ix_monthly_invoice_summary_shop_id'), table_name='monthly_invoice_summary')
    op.drop_table('monthly_invoice_summary')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_staff_members_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_shop_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_staff_code'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_index(op.f('ix_customer_visits_id'), table_name='customer_visits')
    op.drop_index(op.f('ix_customer_visits_shop_id'), table_name='customer_visits')
    op.drop_table('customer_visits')
    op.drop_index(op.f('ix_contact_interactions_id'), table_name='contact_interactions')
    op.drop_index(op.f('ix_contact_interactions_shop_id'), table_name='contact_interactions')
    op.drop_table('contact_interactions')
    op.alter_column('daily_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('daily_records', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('daily_records', 'day',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('daily_records', 'cash_balance',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'average_bill',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'total_cash',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'actual_cash',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'online_sales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'total_sales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'unbilled_sales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'software_figure',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'recorded_sales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'sales_difference',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'cash_reserve',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'expense_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_records', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('daily_records', 'created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('daily_records', 'modified_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('daily_records', 'modified_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_daily_records_date'), table_name='daily_records')
    op.drop_index(op.f('idx_daily_records_shop_id'), table_name='daily_records')
    op.create_index(op.f('ix_daily_records_date'), 'daily_records', ['date'], unique=False)
    op.create_index(op.f('ix_daily_records_id'), 'daily_records', ['id'], unique=False)
    op.create_index(op.f('ix_daily_records_shop_id'), 'daily_records', ['shop_id'], unique=False)
    op.alter_column('notification_reads', 'staff_name',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               nullable=False)
    op.alter_column('notification_reads', 'shop_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_notification_reads_shop_id'), 'notification_reads', ['shop_id'], unique=False)
    op.create_index(op.f('ix_notification_reads_staff_id'), 'notification_reads', ['staff_id'], unique=False)
    op.create_foreign_key(None, 'notification_reads', 'shops', ['shop_id'], ['id'])
    op.alter_column('record_modifications', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_record_modifications_shop_id'), table_name='record_modifications')
    op.alter_column('shops', 'organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('unique_shop_code_per_admin'), 'shops', type_='unique')
    op.create_index(op.f('ix_shops_organization_id'), 'shops', ['organization_id'], unique=False)
    op.create_unique_constraint('unique_shop_code_per_organization', 'shops', ['shop_code', 'organization_id'])
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('admin_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'shops', 'admins', ['admin_id'], ['id'])
    op.drop_constraint('unique_shop_code_per_organization', 'shops', type_='unique')
    op.drop_index(op.f('ix_shops_organization_id'), table_name='shops')
    op.create_unique_constraint(op.f('unique_shop_code_per_admin'), 'shops', ['shop_code', 'admin_id'])
    op.alter_column('shops', 'organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('idx_record_modifications_shop_id'), 'record_modifications', ['shop_id'], unique=False)
    op.alter_column('record_modifications', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'notification_reads', type_='foreignkey')
    op.drop_index(op.f('ix_notification_reads_staff_id'), table_name='notification_reads')
    op.drop_index(op.f('ix_notification_reads_shop_id'), table_name='notification_reads')
    op.alter_column('notification_reads', 'shop_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('notification_reads', 'staff_name',
               existing_type=sa.String(),
               server_default=sa.text('("")'),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_daily_records_shop_id'), table_name='daily_records')
    op.drop_index(op.f('ix_daily_records_id'), table_name='daily_records')
    op.drop_index(op.f('ix_daily_records_date'), table_name='daily_records')
    op.create_index(op.f('idx_daily_records_shop_id'), 'daily_records', ['shop_id'], unique=False)
    op.create_index(op.f('idx_daily_records_date'), 'daily_records', ['date'], unique=False)
    op.alter_column('daily_records', 'modified_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_records', 'modified_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('daily_records', 'created_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_records', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('daily_records', 'expense_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'cash_reserve',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'sales_difference',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'recorded_sales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'software_figure',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'unbilled_sales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'total_sales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'online_sales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'actual_cash',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'total_cash',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'average_bill',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'cash_balance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_records', 'day',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_records', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('daily_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('contact_interactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('staff_code', sa.VARCHAR(), nullable=False),
    sa.Column('interaction_date', sa.DATETIME(), nullable=True),
    sa.Column('interaction_type', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('customer_response', sa.TEXT(), nullable=True),
    sa.Column('next_action', sa.VARCHAR(), nullable=True),
    sa.Column('call_duration', sa.INTEGER(), nullable=True),
    sa.Column('call_successful', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact_records.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_interactions_shop_id'), 'contact_interactions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_contact_interactions_id'), 'contact_interactions', ['id'], unique=False)
    op.create_table('customer_visits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('visit_date', sa.DATETIME(), nullable=True),
    sa.Column('staff_code', sa.VARCHAR(), nullable=False),
    sa.Column('visit_purpose', sa.VARCHAR(), nullable=True),
    sa.Column('prescription_brought', sa.BOOLEAN(), nullable=True),
    sa.Column('purchase_made', sa.BOOLEAN(), nullable=True),
    sa.Column('purchase_amount', sa.FLOAT(), nullable=True),
    sa.Column('staff_notes', sa.TEXT(), nullable=True),
    sa.Column('customer_feedback', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_visits_shop_id'), 'customer_visits', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_visits_id'), 'customer_visits', ['id'], unique=False)
    op.create_table('staff_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('staff_code', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('max_contacts_per_day', sa.INTEGER(), nullable=True),
    sa.Column('total_contacts_assigned', sa.INTEGER(), nullable=True),
    sa.Column('total_conversions', sa.INTEGER(), nullable=True),
    sa.Column('conversion_rate', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_members_staff_code'), 'staff_members', ['staff_code'], unique=1)
    op.create_index(op.f('ix_staff_members_shop_id'), 'staff_members', ['shop_id'], unique=False)
    op.create_index(op.f('ix_staff_members_id'), 'staff_members', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_type', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=False),
    sa.Column('user_phone', sa.VARCHAR(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('shop_name', sa.VARCHAR(), nullable=True),
    sa.Column('shop_location', sa.VARCHAR(), nullable=True),
    sa.Column('organization_id', sa.VARCHAR(), nullable=True),
    sa.Column('admin_name', sa.VARCHAR(), nullable=True),
    sa.Column('admin_phone', sa.VARCHAR(), nullable=True),
    sa.Column('feedback_type', sa.VARCHAR(), nullable=False),
    sa.Column('mood', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('would_recommend', sa.BOOLEAN(), nullable=True),
    sa.Column('satisfaction_rating', sa.INTEGER(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('admin_response', sa.TEXT(), nullable=True),
    sa.Column('responded_by', sa.VARCHAR(), nullable=True),
    sa.Column('responded_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('monthly_invoice_summary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('total_invoices', sa.INTEGER(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('total_items', sa.INTEGER(), nullable=True),
    sa.Column('green_invoices', sa.INTEGER(), nullable=True),
    sa.Column('yellow_invoices', sa.INTEGER(), nullable=True),
    sa.Column('red_invoices', sa.INTEGER(), nullable=True),
    sa.Column('month_color', sa.VARCHAR(), nullable=True),
    sa.Column('overall_sold_percentage', sa.FLOAT(), nullable=True),
    sa.Column('expiring_items_count', sa.INTEGER(), nullable=True),
    sa.Column('expired_items_count', sa.INTEGER(), nullable=True),
    sa.Column('ai_insights', sa.TEXT(), nullable=True),
    sa.Column('movement_prediction', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_invoice_summary_shop_id'), 'monthly_invoice_summary', ['shop_id'], unique=False)
    op.create_index(op.f('ix_monthly_invoice_summary_id'), 'monthly_invoice_summary', ['id'], unique=False)
    op.create_table('customer_medical_conditions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('condition_name', sa.VARCHAR(), nullable=False),
    sa.Column('condition_type', sa.VARCHAR(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('diagnosed_date', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('primary_medicine', sa.VARCHAR(), nullable=True),
    sa.Column('treatment_duration', sa.VARCHAR(), nullable=True),
    sa.Column('requires_monitoring', sa.BOOLEAN(), nullable=True),
    sa.Column('monitoring_frequency', sa.VARCHAR(), nullable=True),
    sa.Column('last_checkup_date', sa.DATE(), nullable=True),
    sa.Column('next_checkup_date', sa.DATE(), nullable=True),
    sa.Column('condition_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_medical_conditions_shop_id'), 'customer_medical_conditions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_medical_conditions_id'), 'customer_medical_conditions', ['id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=False),
    sa.Column('staff_id', sa.INTEGER(), nullable=False),
    sa.Column('staff_name', sa.VARCHAR(), nullable=False),
    sa.Column('bill_number', sa.VARCHAR(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(), nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(), nullable=True),
    sa.Column('customer_email', sa.VARCHAR(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=6), nullable=False),
    sa.Column('payment_reference', sa.VARCHAR(), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=False),
    sa.Column('discount_amount', sa.FLOAT(), nullable=True),
    sa.Column('tax_amount', sa.FLOAT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('amount_paid', sa.FLOAT(), nullable=False),
    sa.Column('change_returned', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('prescription_required', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_staff_id'), 'bills', ['staff_id'], unique=False)
    op.create_index(op.f('ix_bills_shop_id'), 'bills', ['shop_id'], unique=False)
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_bills_customer_phone'), 'bills', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_bills_created_at'), 'bills', ['created_at'], unique=False)
    op.create_index(op.f('ix_bills_bill_number'), 'bills', ['bill_number'], unique=1)
    op.create_table('refill_reminders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('purchase_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('medicine_name', sa.VARCHAR(), nullable=False),
    sa.Column('reminder_date', sa.DATE(), nullable=False),
    sa.Column('notification_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('notification_sent_date', sa.DATETIME(), nullable=True),
    sa.Column('notification_method', sa.VARCHAR(), nullable=True),
    sa.Column('customer_responded', sa.BOOLEAN(), nullable=True),
    sa.Column('customer_purchased', sa.BOOLEAN(), nullable=True),
    sa.Column('response_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['customer_purchases.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refill_reminders_shop_id'), 'refill_reminders', ['shop_id'], unique=False)
    op.create_index(op.f('ix_refill_reminders_id'), 'refill_reminders', ['id'], unique=False)
    op.create_table('call_scripts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('call_type', sa.VARCHAR(), nullable=False),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('customer_summary', sa.TEXT(), nullable=False),
    sa.Column('medical_summary', sa.TEXT(), nullable=True),
    sa.Column('purchase_history_summary', sa.TEXT(), nullable=True),
    sa.Column('key_talking_points', sa.TEXT(), nullable=True),
    sa.Column('medicines_to_discuss', sa.TEXT(), nullable=True),
    sa.Column('follow_up_reminders', sa.TEXT(), nullable=True),
    sa.Column('script_used', sa.BOOLEAN(), nullable=True),
    sa.Column('call_successful', sa.BOOLEAN(), nullable=True),
    sa.Column('customer_response', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_scripts_shop_id'), 'call_scripts', ['shop_id'], unique=False)
    op.create_index(op.f('ix_call_scripts_id'), 'call_scripts', ['id'], unique=False)
    op.create_table('contact_reminders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('staff_code', sa.VARCHAR(), nullable=False),
    sa.Column('reminder_date', sa.DATETIME(), nullable=False),
    sa.Column('reminder_type', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('completed_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact_records.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_reminders_shop_id'), 'contact_reminders', ['shop_id'], unique=False)
    op.create_index(op.f('ix_contact_reminders_id'), 'contact_reminders', ['id'], unique=False)
    op.create_table('customer_purchases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('visit_id', sa.INTEGER(), nullable=True),
    sa.Column('purchase_date', sa.DATETIME(), nullable=True),
    sa.Column('medicine_name', sa.VARCHAR(), nullable=False),
    sa.Column('brand_name', sa.VARCHAR(), nullable=True),
    sa.Column('generic_name', sa.VARCHAR(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('is_generic', sa.BOOLEAN(), nullable=True),
    sa.Column('is_prescription', sa.BOOLEAN(), nullable=True),
    sa.Column('duration_days', sa.INTEGER(), nullable=True),
    sa.Column('refill_reminder_sent', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['customer_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_purchases_shop_id'), 'customer_purchases', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_purchases_id'), 'customer_purchases', ['id'], unique=False)
    op.create_table('purchase_invoice_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('item_code', sa.VARCHAR(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(), nullable=False),
    sa.Column('batch_number', sa.VARCHAR(), nullable=True),
    sa.Column('purchased_quantity', sa.FLOAT(), nullable=False),
    sa.Column('sold_quantity', sa.FLOAT(), nullable=True),
    sa.Column('remaining_quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit_cost', sa.FLOAT(), nullable=False),
    sa.Column('selling_price', sa.FLOAT(), nullable=False),
    sa.Column('total_cost', sa.FLOAT(), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('days_to_expiry', sa.INTEGER(), nullable=True),
    sa.Column('is_expiring_soon', sa.BOOLEAN(), nullable=True),
    sa.Column('is_expiring_critical', sa.BOOLEAN(), nullable=True),
    sa.Column('movement_rate', sa.FLOAT(), nullable=True),
    sa.Column('seasonal_factor', sa.FLOAT(), nullable=True),
    sa.Column('demand_category', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoice_items_item_code'), 'purchase_invoice_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_items_id'), 'purchase_invoice_items', ['id'], unique=False)
    op.create_table('prescription_medicines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('prescription_id', sa.INTEGER(), nullable=True),
    sa.Column('medicine_name', sa.VARCHAR(), nullable=False),
    sa.Column('generic_name', sa.VARCHAR(), nullable=True),
    sa.Column('brand_name', sa.VARCHAR(), nullable=True),
    sa.Column('dosage', sa.VARCHAR(), nullable=False),
    sa.Column('frequency', sa.VARCHAR(), nullable=False),
    sa.Column('duration_days', sa.INTEGER(), nullable=False),
    sa.Column('total_quantity_prescribed', sa.INTEGER(), nullable=False),
    sa.Column('refill_allowed', sa.BOOLEAN(), nullable=True),
    sa.Column('refills_remaining', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('purchased', sa.BOOLEAN(), nullable=True),
    sa.Column('purchase_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['customer_prescriptions.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_medicines_shop_id'), 'prescription_medicines', ['shop_id'], unique=False)
    op.create_index(op.f('ix_prescription_medicines_id'), 'prescription_medicines', ['id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('contact_record_id', sa.INTEGER(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('chronic_conditions', sa.TEXT(), nullable=True),
    sa.Column('allergies', sa.TEXT(), nullable=True),
    sa.Column('preferred_brands', sa.TEXT(), nullable=True),
    sa.Column('first_visit_date', sa.DATETIME(), nullable=True),
    sa.Column('last_visit_date', sa.DATETIME(), nullable=True),
    sa.Column('total_visits', sa.INTEGER(), nullable=True),
    sa.Column('total_purchases', sa.FLOAT(), nullable=True),
    sa.Column('prefers_generic', sa.BOOLEAN(), nullable=True),
    sa.Column('generic_education_given', sa.BOOLEAN(), nullable=True),
    sa.Column('special_notes', sa.TEXT(), nullable=True),
    sa.Column('primary_doctor', sa.TEXT(), nullable=True),
    sa.Column('doctor_phone', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['contact_record_id'], ['contact_records.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_shop_id'), 'customer_profiles', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_phone'), 'customer_profiles', ['phone'], unique=1)
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_table('bill_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=False),
    sa.Column('bill_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_item_id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(), nullable=False),
    sa.Column('batch_number', sa.VARCHAR(), nullable=False),
    sa.Column('generic_name', sa.VARCHAR(), nullable=True),
    sa.Column('brand_name', sa.VARCHAR(), nullable=True),
    sa.Column('rack_number', sa.VARCHAR(), nullable=True),
    sa.Column('section_name', sa.VARCHAR(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('discount_percent', sa.FLOAT(), nullable=True),
    sa.Column('discount_amount', sa.FLOAT(), nullable=True),
    sa.Column('tax_percent', sa.FLOAT(), nullable=True),
    sa.Column('tax_amount', sa.FLOAT(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items_audit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_items_shop_id'), 'bill_items', ['shop_id'], unique=False)
    op.create_index(op.f('ix_bill_items_id'), 'bill_items', ['id'], unique=False)
    op.create_table('purchase_invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(), nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(), nullable=False),
    sa.Column('invoice_date', sa.DATE(), nullable=False),
    sa.Column('received_date', sa.DATE(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('total_items', sa.INTEGER(), nullable=False),
    sa.Column('total_quantity', sa.FLOAT(), nullable=False),
    sa.Column('sold_percentage', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('color_code', sa.VARCHAR(), nullable=True),
    sa.Column('has_expiring_items', sa.BOOLEAN(), nullable=True),
    sa.Column('nearest_expiry_days', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoices_shop_id'), 'purchase_invoices', ['shop_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_received_date'), 'purchase_invoices', ['received_date'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_invoice_number'), 'purchase_invoices', ['invoice_number'], unique=1)
    op.create_index(op.f('ix_purchase_invoices_invoice_date'), 'purchase_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_id'), 'purchase_invoices', ['id'], unique=False)
    op.create_table('customer_prescriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('prescription_date', sa.DATE(), nullable=False),
    sa.Column('doctor_name', sa.VARCHAR(), nullable=False),
    sa.Column('doctor_phone', sa.VARCHAR(), nullable=True),
    sa.Column('clinic_name', sa.VARCHAR(), nullable=True),
    sa.Column('condition_name', sa.VARCHAR(), nullable=False),
    sa.Column('condition_severity', sa.VARCHAR(), nullable=True),
    sa.Column('is_chronic', sa.BOOLEAN(), nullable=True),
    sa.Column('next_followup_date', sa.DATE(), nullable=True),
    sa.Column('followup_type', sa.VARCHAR(), nullable=True),
    sa.Column('followup_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('completion_date', sa.DATE(), nullable=True),
    sa.Column('prescription_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_prescriptions_shop_id'), 'customer_prescriptions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_prescriptions_id'), 'customer_prescriptions', ['id'], unique=False)
    op.create_table('expiry_alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('alert_type', sa.VARCHAR(), nullable=False),
    sa.Column('alert_date', sa.DATE(), nullable=False),
    sa.Column('is_acknowledged', sa.BOOLEAN(), nullable=True),
    sa.Column('acknowledged_by', sa.VARCHAR(), nullable=True),
    sa.Column('acknowledged_at', sa.DATETIME(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['purchase_invoice_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expiry_alerts_id'), 'expiry_alerts', ['id'], unique=False)
    op.create_table('contact_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_status', sa.VARCHAR(), nullable=True),
    sa.Column('contact_status', sa.VARCHAR(), nullable=True),
    sa.Column('source_file', sa.VARCHAR(), nullable=True),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), nullable=True),
    sa.Column('assigned_staff_code', sa.VARCHAR(), nullable=True),
    sa.Column('assigned_date', sa.DATETIME(), nullable=True),
    sa.Column('first_contact_date', sa.DATETIME(), nullable=True),
    sa.Column('last_contact_date', sa.DATETIME(), nullable=True),
    sa.Column('contact_attempts', sa.INTEGER(), nullable=True),
    sa.Column('whatsapp_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('whatsapp_sent_date', sa.DATETIME(), nullable=True),
    sa.Column('converted_date', sa.DATETIME(), nullable=True),
    sa.Column('conversion_value', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_records_shop_id'), 'contact_records', ['shop_id'], unique=False)
    op.create_index(op.f('ix_contact_records_phone'), 'contact_records', ['phone'], unique=1)
    op.create_index(op.f('ix_contact_records_id'), 'contact_records', ['id'], unique=False)
    op.create_table('contact_uploads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('file_type', sa.VARCHAR(), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), nullable=True),
    sa.Column('processed', sa.BOOLEAN(), nullable=True),
    sa.Column('processing_date', sa.DATETIME(), nullable=True),
    sa.Column('total_contacts', sa.INTEGER(), nullable=True),
    sa.Column('whatsapp_contacts', sa.INTEGER(), nullable=True),
    sa.Column('non_whatsapp_contacts', sa.INTEGER(), nullable=True),
    sa.Column('duplicate_contacts', sa.INTEGER(), nullable=True),
    sa.Column('processing_errors', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_uploads_shop_id'), 'contact_uploads', ['shop_id'], unique=False)
    op.create_index(op.f('ix_contact_uploads_id'), 'contact_uploads', ['id'], unique=False)
    op.create_table('item_sales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('sale_date', sa.DATE(), nullable=False),
    sa.Column('quantity_sold', sa.FLOAT(), nullable=False),
    sa.Column('sale_price', sa.FLOAT(), nullable=False),
    sa.Column('profit_margin', sa.FLOAT(), nullable=False),
    sa.Column('customer_type', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['purchase_invoice_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_sales_sale_date'), 'item_sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_item_sales_id'), 'item_sales', ['id'], unique=False)
    # ### end Alembic commands ###
